from enum import Enum


class GovernanceState(Enum):
    OBSERVED = "OBSERVED"
    ASSESSED = "ASSESSED"
    DECIDED = "DECIDED"
    COMMITTED = "COMMITTED"
    ACKED = "ACKED"
    CLOSED = "CLOSED"


class GovernanceEventType(Enum):
    OBSERVATION_RECORDED = "OBSERVATION_RECORDED"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    DECISION_MADE = "DECISION_MADE"
    COMMITMENT_RECORDED = "COMMITMENT_RECORDED"
    ACKNOWLEDGMENT_RECEIVED = "ACKNOWLEDGMENT_RECEIVED"
    CYCLE_CLOSED = "CYCLE_CLOSED"
    THREAT_DETECTED = "THREAT_DETECTED"
    COMPATIBILITY_NEGOTIATED = "COMPATIBILITY_NEGOTIATED"
