from enum import Enum


class SymbolicRefusalReason(Enum):
    REDTEAM_OVERLAY_DETECTED = "REDTEAM_OVERLAY_DETECTED"
    ML_HARD_BLOCK_LIVE_TRAINING = "ML_HARD_BLOCK_LIVE_TRAINING"
    INVARIANT_VIOLATED = "INVARIANT_VIOLATED"
    GOVERNANCE_CONSTRAINT_FAILED = "GOVERNANCE_CONSTRAINT_FAILED"
